### ISSUE TITLE
Running with --network=host produces FATAL

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/docker#67]
```
[box@github ~]$ docker run --rm --network host manticoresearch/manticore:dev-6.2.13-69cd5a6
hostname: Name or service not known
[Thu Dec  7 07:19:35.174 2023] [1] using config file '/etc/manticoresearch/manticore.conf.sh' (375 chars)...
starting daemon version '6.2.13 69cd5a61f@231207 dev' ...
listening on all interfaces for mysql, port=9306
listening on UNIX socket /var/run/mysqld/mysqld.sock
listening on all interfaces for sphinx and http(s), port=9308
FATAL: port 0 is out of range
shutdown daemon version '6.2.13 69cd5a61f@231207 dev' ...
shutdown complete
Manticore 6.2.13 69cd5a61f@231207 dev
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2023, Manticore Software LTD (https://manticoresearch.com)
```

**Comment by djklim87** [comment]
All works fine. Can you add more details?

```
klim@klim-BOHK-WAX9X:~$ docker run --rm --network host manticoresearch/manticore:dev-6.2.13-69cd5a6
[Fri Dec 22 16:18:10.112 2023] [1] using config file '/etc/manticoresearch/manticore.conf.sh' (393 chars)...
starting daemon version '6.2.13 69cd5a61f@231207 dev' ...
listening on all interfaces for mysql, port=9306
listening on UNIX socket /var/run/mysqld/mysqld.sock
listening on all interfaces for sphinx and http(s), port=9308
listening on 127.0.1.1:9312 for sphinx and http(s)
prereading 0 tables
preread 0 tables in 0.000 sec
accepting connections
```

**Comment by sanikolaev** [comment]
DMITRII has reproduced it on `github`. DMITRII will let Klim know how to log in to `github` to reproduce the issue.

**Comment by djklim87** [comment]
For correct execution, we need the `hostname -i` command. 
In case we run this command on a specified server with `--network=host` flag, we get an error:

```
[box@github ~]$ docker run --network host -it --rm ubuntu:focal hostname -i
hostname: Name or service not known
``` 

In [this](https://github.com/manticoresoftware/docker/pull/70) PR I added some round ways with `hostname -I` and hardcode `0.0.0.0` host in case all host's commands before failed

**Comment by djklim87** [comment]
Waiting until CI builds new docker image for test

**Comment by djklim87** [comment]
Done

**Comment by donhardman** [comment]
The problem still persists. The current issue is that when we set the `hostname` while running the container, we are unable to run it because the IP detected is incorrect.

```
docker run --rm --hostname manticore --network host manticoresearch/manticore:dev-6.3.7-626b327
```

log:
```
[Thu Sep 12 01:26:08.431 2024] [1] using config file '/etc/manticoresearch/manticore.conf.sh' (401 chars)...
starting daemon version '6.3.7 626b32779@24091010 dev' ...
listening on all interfaces for mysql, port=9306
listening on UNIX socket /var/run/mysqld/mysqld.sock
listening on all interfaces for sphinx and http(s), port=9308
listening on 172.66.44.141:9312 for sphinx and http(s)
bind() failed on 172.66.44.141, retrying...
^Cbind() failed on 172.66.44.141, retrying...


^Cbind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
bind() failed on 172.66.44.141, retrying...
FATAL: bind() failed on 172.66.44.141: Cannot assign requested address
shutdown daemon version '6.3.7 626b32779@24091010 dev' ...
shutdown complete
Manticore 6.3.7 626b32779@24091010 dev
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)
```

**Comment by sanikolaev** [comment]
This works for me on dev2:

```
snikolaev@dev2:~$ docker run --rm --hostname manticore --name manticore --network host manticoresearch/manticore:dev-6.3.7-626b327
[Thu Sep 12 08:37:24.737 2024] [1] using config file '/etc/manticoresearch/manticore.conf.sh' (405 chars)...
starting daemon version '6.3.7 626b32779@24091010 dev' ...
listening on all interfaces for mysql, port=9306
listening on UNIX socket /var/run/mysqld/mysqld.sock
listening on all interfaces for sphinx and http(s), port=9308
listening on 148.251.234.230:9312 for sphinx and http(s)
prereading 0 tables
preread 0 tables in 0.000 sec
accepting connections
```

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/docker/pull/94
